development:
  adapter: mysql2
  encoding: utf8
  database: ef_development
  host: localhost
  pool: 5
  username: root
  password: sqlpass

test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: ef_test
  pool: 5
  username: root
  password: sqlpass
